set_property PACKAGE_PIN W4 [get_ports enables[3] ]
set_property IOSTANDARD LVCMOS33 [get_ports enables[3]]
set_property PACKAGE_PIN U4 [get_ports enables[2]]
set_property IOSTANDARD LVCMOS33 [get_ports enables[2]]
set_property PACKAGE_PIN V4 [get_ports enables[1]]
set_property IOSTANDARD LVCMOS33 [get_ports enables[1]]
set_property PACKAGE_PIN U2 [get_ports enables[0]]
set_property IOSTANDARD LVCMOS33 [get_ports enables[0]]
set_property PACKAGE_PIN W5 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property PACKAGE_PIN W7 [get_ports disp[6]]
set_property IOSTANDARD LVCMOS33 [get_ports disp[6]]
set_property PACKAGE_PIN W6 [get_ports disp[5]]
set_property IOSTANDARD LVCMOS33 [get_ports disp[5]]
set_property PACKAGE_PIN U8 [get_ports disp[4]]
set_property IOSTANDARD LVCMOS33 [get_ports disp[4]]
set_property PACKAGE_PIN V8 [get_ports disp[3]]
set_property IOSTANDARD LVCMOS33 [get_ports disp[3]]
set_property PACKAGE_PIN U5 [get_ports disp[2]]
set_property IOSTANDARD LVCMOS33 [get_ports disp[2]]
set_property PACKAGE_PIN V5 [get_ports disp[1]]
set_property IOSTANDARD LVCMOS33 [get_ports disp[1]]
set_property PACKAGE_PIN U7 [get_ports disp[0]]
set_property IOSTANDARD LVCMOS33 [get_ports disp[0]]

set_property PACKAGE_PIN B18 [get_ports A]
set_property IOSTANDARD LVCMOS33 [get_ports A]

set_property PACKAGE_PIN L1 [get_ports sign]
set_property IOSTANDARD LVCMOS33 [get_ports sign]
set_property PACKAGE_PIN P1 [get_ports x]
set_property IOSTANDARD LVCMOS33 [get_ports x]
set_property PACKAGE_PIN N3 [get_ports y]
set_property IOSTANDARD LVCMOS33 [get_ports y]
set_property PACKAGE_PIN P3 [get_ports z]
set_property IOSTANDARD LVCMOS33 [get_ports z]
set_property PACKAGE_PIN U3 [get_ports zero]
set_property IOSTANDARD LVCMOS33 [get_ports zero]
set_property PACKAGE_PIN W3 [get_ports u]
set_property IOSTANDARD LVCMOS33 [get_ports u]


set_property PACKAGE_PIN V13 [get_ports check[3]]
set_property IOSTANDARD LVCMOS33 [get_ports check[3]]
set_property PACKAGE_PIN V14 [get_ports check[2]]
set_property IOSTANDARD LVCMOS33 [get_ports check[2]]
set_property PACKAGE_PIN U14 [get_ports check[1]]
set_property IOSTANDARD LVCMOS33 [get_ports check[1]]
set_property PACKAGE_PIN U15 [get_ports check[0]]
set_property IOSTANDARD LVCMOS33 [get_ports check[0]]
